app:
  name: "matching"
  mode: "dev"
  port: ":3001"

log:
  level: "debug"
  infoFilename: "../log/info.log"
  errFilename: "../log/error.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "kob"
  max_idle_conns: 10
  max_open_conns: 30