// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true;uniqueIndex:user_id_uindex,priority:1" json:"id"`
	Username string `gorm:"column:username" json:"username"`
	Password string `gorm:"column:password" json:"password"`
	Photo    string `gorm:"column:photo" json:"photo"`
	Rating   *int32 `gorm:"column:rating;default:1500" json:"rating"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
