// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: snake.proto

package game_system

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AId    int32 `protobuf:"varint,1,opt,name=aId,proto3" json:"aId,omitempty"`
	ABotId int32 `protobuf:"varint,2,opt,name=aBotId,proto3" json:"aBotId,omitempty"`
	BId    int32 `protobuf:"varint,3,opt,name=bId,proto3" json:"bId,omitempty"`
	BBotId int32 `protobuf:"varint,4,opt,name=bBotId,proto3" json:"bBotId,omitempty"`
}

func (x *StartGameReq) Reset() {
	*x = StartGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameReq) ProtoMessage() {}

func (x *StartGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameReq.ProtoReflect.Descriptor instead.
func (*StartGameReq) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{0}
}

func (x *StartGameReq) GetAId() int32 {
	if x != nil {
		return x.AId
	}
	return 0
}

func (x *StartGameReq) GetABotId() int32 {
	if x != nil {
		return x.ABotId
	}
	return 0
}

func (x *StartGameReq) GetBId() int32 {
	if x != nil {
		return x.BId
	}
	return 0
}

func (x *StartGameReq) GetBBotId() int32 {
	if x != nil {
		return x.BBotId
	}
	return 0
}

type StartGameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StartGameResp) Reset() {
	*x = StartGameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResp) ProtoMessage() {}

func (x *StartGameResp) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResp.ProtoReflect.Descriptor instead.
func (*StartGameResp) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{1}
}

func (x *StartGameResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetNextStepReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction string `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	PlayerId  string `protobuf:"bytes,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
}

func (x *SetNextStepReq) Reset() {
	*x = SetNextStepReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNextStepReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNextStepReq) ProtoMessage() {}

func (x *SetNextStepReq) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNextStepReq.ProtoReflect.Descriptor instead.
func (*SetNextStepReq) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{2}
}

func (x *SetNextStepReq) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *SetNextStepReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type SetNextStepResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event      string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	ADirection int32    `protobuf:"varint,2,opt,name=aDirection,proto3" json:"aDirection,omitempty"`
	BDirection int32    `protobuf:"varint,3,opt,name=bDirection,proto3" json:"bDirection,omitempty"`
	GameMap    *GameMap `protobuf:"bytes,4,opt,name=gameMap,proto3" json:"gameMap,omitempty"`
	Loser      string   `protobuf:"bytes,5,opt,name=loser,proto3" json:"loser,omitempty"`
}

func (x *SetNextStepResp) Reset() {
	*x = SetNextStepResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNextStepResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNextStepResp) ProtoMessage() {}

func (x *SetNextStepResp) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNextStepResp.ProtoReflect.Descriptor instead.
func (*SetNextStepResp) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{3}
}

func (x *SetNextStepResp) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *SetNextStepResp) GetADirection() int32 {
	if x != nil {
		return x.ADirection
	}
	return 0
}

func (x *SetNextStepResp) GetBDirection() int32 {
	if x != nil {
		return x.BDirection
	}
	return 0
}

func (x *SetNextStepResp) GetGameMap() *GameMap {
	if x != nil {
		return x.GameMap
	}
	return nil
}

func (x *SetNextStepResp) GetLoser() string {
	if x != nil {
		return x.Loser
	}
	return ""
}

type GameMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AId     int32   `protobuf:"varint,1,opt,name=AId,proto3" json:"AId,omitempty"`
	ASx     int32   `protobuf:"varint,2,opt,name=ASx,proto3" json:"ASx,omitempty"`
	ASy     int32   `protobuf:"varint,3,opt,name=ASy,proto3" json:"ASy,omitempty"`
	BId     int32   `protobuf:"varint,4,opt,name=BId,proto3" json:"BId,omitempty"`
	BSx     int32   `protobuf:"varint,5,opt,name=BSx,proto3" json:"BSx,omitempty"`
	BSy     int32   `protobuf:"varint,6,opt,name=BSy,proto3" json:"BSy,omitempty"`
	GameMap []*Edge `protobuf:"bytes,7,rep,name=GameMap,proto3" json:"GameMap,omitempty"`
	PlayerA *User   `protobuf:"bytes,8,opt,name=playerA,proto3" json:"playerA,omitempty"`
	PlayerB *User   `protobuf:"bytes,9,opt,name=playerB,proto3" json:"playerB,omitempty"`
}

func (x *GameMap) Reset() {
	*x = GameMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMap) ProtoMessage() {}

func (x *GameMap) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMap.ProtoReflect.Descriptor instead.
func (*GameMap) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{4}
}

func (x *GameMap) GetAId() int32 {
	if x != nil {
		return x.AId
	}
	return 0
}

func (x *GameMap) GetASx() int32 {
	if x != nil {
		return x.ASx
	}
	return 0
}

func (x *GameMap) GetASy() int32 {
	if x != nil {
		return x.ASy
	}
	return 0
}

func (x *GameMap) GetBId() int32 {
	if x != nil {
		return x.BId
	}
	return 0
}

func (x *GameMap) GetBSx() int32 {
	if x != nil {
		return x.BSx
	}
	return 0
}

func (x *GameMap) GetBSy() int32 {
	if x != nil {
		return x.BSy
	}
	return 0
}

func (x *GameMap) GetGameMap() []*Edge {
	if x != nil {
		return x.GameMap
	}
	return nil
}

func (x *GameMap) GetPlayerA() *User {
	if x != nil {
		return x.PlayerA
	}
	return nil
}

func (x *GameMap) GetPlayerB() *User {
	if x != nil {
		return x.PlayerB
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Edge []int32 `protobuf:"varint,1,rep,packed,name=edge,proto3" json:"edge,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{5}
}

func (x *Edge) GetEdge() []int32 {
	if x != nil {
		return x.Edge
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Photo    string `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserID   int32  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

var File_snake_proto protoreflect.FileDescriptor

var file_snake_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x62, 0x22, 0x62, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x42, 0x6f, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x42, 0x6f, 0x74, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x62, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x62,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x42, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x62, 0x42, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4a, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x78, 0x74,
	0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x22, 0xa9, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x74, 0x65,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x61, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x62,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x62, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x07,
	0x67, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x73, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x73, 0x65, 0x72, 0x22, 0xf0, 0x01,
	0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x41,
	0x53, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x53, 0x78, 0x12, 0x10, 0x0a,
	0x03, 0x41, 0x53, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x53, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x42, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x42, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x53, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x42, 0x53, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x53, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x42, 0x53, 0x79, 0x12, 0x27, 0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x70,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x64, 0x67, 0x65, 0x52, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x27,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42,
	0x22, 0x1a, 0x0a, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x64, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x65, 0x64, 0x67, 0x65, 0x22, 0x50, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x32, 0x93,
	0x01, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x3c,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b,
	0x53, 0x65, 0x74, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x74, 0x65, 0x70, 0x12, 0x17, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x74, 0x65,
	0x70, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x74, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snake_proto_rawDescOnce sync.Once
	file_snake_proto_rawDescData = file_snake_proto_rawDesc
)

func file_snake_proto_rawDescGZIP() []byte {
	file_snake_proto_rawDescOnce.Do(func() {
		file_snake_proto_rawDescData = protoimpl.X.CompressGZIP(file_snake_proto_rawDescData)
	})
	return file_snake_proto_rawDescData
}

var file_snake_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_snake_proto_goTypes = []interface{}{
	(*StartGameReq)(nil),    // 0: game.pb.StartGameReq
	(*StartGameResp)(nil),   // 1: game.pb.StartGameResp
	(*SetNextStepReq)(nil),  // 2: game.pb.SetNextStepReq
	(*SetNextStepResp)(nil), // 3: game.pb.SetNextStepResp
	(*GameMap)(nil),         // 4: game.pb.GameMap
	(*Edge)(nil),            // 5: game.pb.Edge
	(*User)(nil),            // 6: game.pb.User
}
var file_snake_proto_depIdxs = []int32{
	4, // 0: game.pb.SetNextStepResp.gameMap:type_name -> game.pb.GameMap
	5, // 1: game.pb.GameMap.GameMap:type_name -> game.pb.Edge
	6, // 2: game.pb.GameMap.playerA:type_name -> game.pb.User
	6, // 3: game.pb.GameMap.playerB:type_name -> game.pb.User
	0, // 4: game.pb.game_system.StartGame:input_type -> game.pb.StartGameReq
	2, // 5: game.pb.game_system.SetNextStep:input_type -> game.pb.SetNextStepReq
	1, // 6: game.pb.game_system.StartGame:output_type -> game.pb.StartGameResp
	3, // 7: game.pb.game_system.SetNextStep:output_type -> game.pb.SetNextStepResp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_snake_proto_init() }
func file_snake_proto_init() {
	if File_snake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNextStepReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNextStepResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snake_proto_goTypes,
		DependencyIndexes: file_snake_proto_depIdxs,
		MessageInfos:      file_snake_proto_msgTypes,
	}.Build()
	File_snake_proto = out.File
	file_snake_proto_rawDesc = nil
	file_snake_proto_goTypes = nil
	file_snake_proto_depIdxs = nil
}
