// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRecord = "record"

// Record mapped from table <record>
type Record struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;uniqueIndex:record_id_uindex,priority:1" json:"id"`
	AID        int32     `gorm:"column:a_id" json:"a_id"`
	ASx        int32     `gorm:"column:a_sx" json:"a_sx"`
	ASy        int32     `gorm:"column:a_sy" json:"a_sy"`
	BID        int32     `gorm:"column:b_id" json:"b_id"`
	BSx        int32     `gorm:"column:b_sx" json:"b_sx"`
	BSy        int32     `gorm:"column:b_sy" json:"b_sy"`
	ASteps     string    `gorm:"column:a_steps" json:"a_steps"`
	BSteps     string    `gorm:"column:b_steps" json:"b_steps"`
	Map        string    `gorm:"column:map" json:"map"`
	Loser      string    `gorm:"column:loser" json:"loser"`
	Createtime time.Time `gorm:"column:createtime" json:"createtime"`
}

// TableName Record's table name
func (*Record) TableName() string {
	return TableNameRecord
}
